# ALE settings export
self_address=DL3HC
station_file=EUR.ale
assumed_scan_channels=10
golay_mode=3
min_unanimous_votes=33
adaptive_fec=0
debug_rx=0
manual_accept_mode=1
manual_accept_timeout_ms=20000
scan_dwell_ms=200
sounding_interval_sec=20
sounding_use_twas=0
sounding_warning_lead_sec=10
link_idle_timeout_sec=360
max_tune_time_ms=1045
ptt_lead_ms=10
ptt_tail_ms=200
lqa_exchange_enabled=1
lqa_enabled=1
relink_enabled=0
relink_improvement_threshold=5
enhanced_freq_select=0
position_source=2
station_lat_deg=52.5208
station_lon_deg=9.45833
grid_locator=JO42rm
gpsd_host=127.0.0.1
gpsd_port=2947
nmea_port=
nmea_baud=4800
sfi_enabled=1

# ALE address export
# contact=callsign|name|status|net_members|valid_channels
contact=DF3SR||enabled||ALL
audio_in=CABLE-A Output (VB-Audio Virtual Cable A)
audio_out=CABLE-B Input (VB-Audio Virtual Cable B)
