# ALE settings export
self_address=DL3HC
channel_file=
assumed_scan_channels=10
golay_mode=3
min_unanimous_votes=33
adaptive_fec=0
debug_rx=0
manual_accept_mode=1
manual_accept_timeout_ms=20000
scan_dwell_ms=200
sounding_interval_sec=300
link_idle_timeout_sec=360
max_tune_time_ms=1045
ptt_lead_ms=100
ptt_tail_ms=350
lqa_exchange_enabled=1
lqa_enabled=1
relink_enabled=0
relink_improvement_threshold=5
enhanced_freq_select=0
net=NET1
net_channel=NET1:C-1
net_channel=NET1:C-2
net_channel=NET1:C-3
net_channel=NET1:C-4
audio_in=CABLE-A Output (VB-Audio Virtual Cable A)
audio_out=CABLE-B Input (VB-Audio Virtual Cable B)
